FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Salin dependencies dan install
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin seluruh kode aplikasi
COPY app/ .

# Jalankan FastAPI dengan Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]